const FavoritesActionTypes = {
  FETCH_FAVORITES_START: "FETCH_FAVORITES_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
  REMOVE_FAV_ITEM: "REMOVE_FAV_ITEM",
};

export default FavoritesActionTypes;
