const FavoritesActionTypes = {
  FETCH_FAVORITES_START: "FETCH_FAVORITES_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
};

export default FavoritesActionTypes;
